###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

version: '3'
services:

  #############################################################################################################
  # The "workflow" container is running Workflow Process Service
  #############################################################################################################
  workflow:
    # un-comment the following line if you plan to run the Authoring environment
    image: cp.icr.io/cp/cp4a/workflow-ps/workflow-ps-authoring:22.0.1
    # ...or un-comment the following line if you plan to run the Process Server environment
    # image: cp.icr.io/cp/cp4a/workflow-ps/workflow-ps-server:22.0.1
    container_name: workflow
    hostname: workflow
    ports:
      - "9443:9443"
    volumes:

      # This volume contains the data which has to be persisted across restarts
      - workflow_runtime_data:/shared/custom/data:z

      # This volume contains logs and heap dumps generated by the container
      - workflow_runtime_logs:/shared/custom/output:z

      # If the Postgres is exposed securely using SSL, you must mount the root certificate which was used to
      # sign the Postgres server certificate so the client can verify that the server's leaf certificate was
      # signed by its trusted root certificate.
      - ./config/cert-trusted/db_root.crt:/shared/custom/cert-trusted/db_root.crt:Z

      ###########################################################################################################
      # Uncomment any of the following lines to customize the Workflow Process Service runtime by mounting
      # files as appropriate
      ###########################################################################################################

      # Custom Liberty configuration dropin (like custom logging, custom user registry). You can mount any file
      # containing Liberty configurattion dropins in the /config/configDropins/overrides folder
      # - ./config/liberty/logging.xml:/config/configDropins/overrides/logging.xml
      # - ./config/liberty/liberty-custom.xml:/config/configDropins/overrides/liberty-custom.xml

      # Custom Workflow configuration
      # - ./config/workflow/workflow-custom.xml:/config/config/workflow-custom.xml:Z

      # Provide your own passwords and functional user credentials
      # - ./config/env/server.env:/shared/custom/env/server.env:Z


      # If you want to provide your own keystore and truststore, you can put the appropriate files in
      # ./config/tls folder and uncomment the following lines.
      # If these files are not provided, they will be generated upon start.
      # - ./config/tls/key.p12:/shared/custom/tls/key.p12:Z
      # - ./config/tls/trusts.p12:/shared/custom/tls/trusts.p12
      # If you aslo enable full text search, please also provide corresponding trust store jks file.
      # - ./config/tls/trusts.p12:/shared/custom/tls/trusts.jks

      # If PFS is enabled and Elasticsearch is exposed using a TLS self-signed certificate and the keystore and
      # truststore are generated, you have to provide the Elasticsearch certificate so that it gets added
      # to the truststore when generating it. This can be performed by adding the certificate in PEM format to
      # the ./config/cert-trusted folder (the filename must end with either .pem or .crt extension), and
      # un-comment the following line
      # - ./config/cert-trusted/es_crt.pem:/shared/custom/cert-trusted/es_crt.pem

      # If LDAP is used securely using SSL, you must mount the root certificate which was used to
      # sign the LDAP server certificate so that the client can verify that the server's leaf certificate was
      # signed by its trusted root certificate.
      # - ./config/cert-trusted/ldap-cacert.crt:/shared/custom/cert-trusted/ldap-cacert.crt

      # If IDP is used securely using SSL, you must mount the root certificate which was used to
      # sign the IDP server certificate so that the client can verify that the server's leaf certificate was
      # signed by its trusted root certificate.
      # - ./config/cert-trusted/idp-cert.pem:/shared/custom/cert-trusted/idp-cert.pem

      # SAML IDP Metadata configuration
      #  - ./config/liberty/idpMetadata.xml:/config/configDropins/overrides/idpMetadata.xml


    environment:
      - LICENSE=accept
      - LICENSE_TYPE=Production
      # If you want to enable full text search and dashboarding support in Workplace, you must setup Elasticsearch
      # and uncomment and configure the following lines as appropriate to reference Elasticsearch
      # - PFS_ENABLE=true
      # - PFS_REMOTEELASTICSEARCH_ENDPOINTS=https://elasticsearch:9200
      # - PFS_REMOTEELASTICSEARCH_USERNAME=esuser
      # - PFS_REMOTEELASTICSEARCH_PASSWORD=espwd

      # The external hostname. This should not be localhost, but rather, the actual hostname of the docker machine
      - EXTERNAL_HOSTNAME=localhost
      - EXTERNAL_HTTPS_PORT=9443

      # Database connectivity information.
      - DB_DATABASE_NAME=workflowdb
      - DB_SERVER_NAME=postgres.database.hostname
      - DB_SERVER_PORT=5432
      - DB_USERNAME=workflowadmin
      - DB_PASSWORD=password
      - DB_ENABLE_SSL=true
      - DB_SSLMODE=require
      - DB_SSL_CERT_LOCATION=/shared/custom/cert-trusted/db_root.crt

      # admin user name
      - ADMIN_USERNAME=admin

      # user friendly logs
      - WLP_LOGGING_CONSOLE_FORMAT=SIMPLE
      - WLP_LOGGING_MESSAGE_FORMAT=SIMPLE

    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

volumes:
  # Volume sotring data to persist accross restarts
  workflow_runtime_data:
  # Volume storing logs, FFDCs and heap dumps
  workflow_runtime_logs:
    # If you want the logs to be persisted in the same directory as the folder containing the
    # docker-compose.yml file:
    # - ensure that you have docker-compose 1.29 or later
    # - if you are on linux, change this folder ownership to grant RW access to dba-user (id=50001)
    # - and then un-comment the following lines:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: "$PWD/"


networks:
  default:
    driver: bridge
